# Generated by Django 4.1 on 2022-08-25 03:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventProps', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventprop',
            name='dislikes',
        ),
        migrations.RemoveField(
            model_name='eventprop',
            name='image',
        ),
        migrations.RemoveField(
            model_name='eventprop',
            name='likes',
        ),
        migrations.RemoveField(
            model_name='eventprop',
            name='location',
        ),
        migrations.RemoveField(
            model_name='eventprop',
            name='rate',
        ),
        migrations.RemoveField(
            model_name='eventprop',
            name='time',
        ),
        migrations.RemoveField(
            model_name='eventprop',
            name='website',
        ),
    ]
