# Generated by Django 4.1 on 2022-08-26 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventProps', '0002_remove_eventprop_dislikes_remove_eventprop_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventprop',
            name='name',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='eventprop',
            name='price',
            field=models.TextField(),
        ),
    ]
