# Generated by Django 4.1 on 2022-08-28 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventProps', '0004_alter_eventprop_name_alter_eventprop_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventprop',
            name='price',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
