# Generated by Django 4.1 on 2022-08-28 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventProps', '0005_alter_eventprop_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventprop',
            name='price',
        ),
    ]
