# Generated by Django 4.1 on 2022-08-28 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventProps', '0006_remove_eventprop_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventprop',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='eventprop',
            name='name',
            field=models.CharField(default='', max_length=255),
        ),
    ]
