# Generated by Django 4.1 on 2022-08-28 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventProps', '0007_alter_eventprop_description_alter_eventprop_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventprop',
            name='name',
            field=models.TextField(default=''),
        ),
    ]
